.PHONY: clean All

All:
	@echo "----------Building project:[ CString - Debug ]----------"
	@cd "CString" && "$(MAKE)" -f  "CString.mk"
clean:
	@echo "----------Cleaning project:[ CString - Debug ]----------"
	@cd "CString" && "$(MAKE)" -f  "CString.mk" clean
